// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModelBuilderDemo.Data;

#nullable disable

namespace ModelBuilderDemo.Migrations
{
    [DbContext(typeof(ModelBuilderDemoContext))]
    partial class ModelBuilderDemoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ModelBuilderDemo.Models.Course", b =>
                {
                    b.Property<string>("CourseNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Course Title");

                    b.HasKey("CourseNumber");

                    b.ToTable("Course", (string)null);

                    b.HasData(
                        new
                        {
                            CourseNumber = "ef3fc486-c8c2-41d8-bc68-2b528439d03a",
                            Title = "ModelBuilder Introduction"
                        });
                });

            modelBuilder.Entity("ModelBuilderDemo.Models.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AttendingCourseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuditingCourseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("AttendingCourseNumber");

                    b.HasIndex("AuditingCourseNumber");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("ModelBuilderDemo.Models.Student", b =>
                {
                    b.HasOne("ModelBuilderDemo.Models.Course", "AttendingCourse")
                        .WithMany("AttendingStudents")
                        .HasForeignKey("AttendingCourseNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelBuilderDemo.Models.Course", "AuditingCourse")
                        .WithMany("AuditingStudents")
                        .HasForeignKey("AuditingCourseNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttendingCourse");

                    b.Navigation("AuditingCourse");
                });

            modelBuilder.Entity("ModelBuilderDemo.Models.Course", b =>
                {
                    b.Navigation("AttendingStudents");

                    b.Navigation("AuditingStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
